on: [push, pull_request]

name: Check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} check

    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'macOS-10.15', 'ubuntu-20.04' ]

    steps:
      - uses: actions/checkout@v2

      - uses: s-u/R-actions/pkg-check@master
        with:
          debian-deps: libgmp-dev libmpfr-dev
          macos-deps: gmp-6.2.1 mpfr-4.0.2
          check-flags: --as-cran

      - name: test gmp
        shell: bash
        run: |
          ## test this binary
          R -e "S <- gmp::Stirling2(50,10)"
          ## test CRAN binary
          R -e "install.packages('gmp', repos = 'https://mac.r-project.org')"
          R -e "S <- gmp::Stirling2(50,10)"
